<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Interligando Dados e Construindo Narrativas – O Mercado de Trabalho Formal de Arqueólogos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./notas.html" rel="next">
<link href="./admitidos.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-377ea77c6c8207fca55e2638f7d4a50d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Procurar",
    "search-label": "Procurar"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./narrativas.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Interligando Dados e Construindo Narrativas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">O Mercado de Trabalho Formal de Arqueólogos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/machadotm/Novos_Dados_MTE_Arqueo" title="Repositório dos dados tratados da RAIS e do Novo CAGED" class="quarto-navigation-tool px-1" aria-label="Repositório dos dados tratados da RAIS e do Novo CAGED"><i class="bi bi-github"></i></a>
    <a href="https://github.com/machadotm/dados_mte_rais_arqueo_22-24" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Notas Introdutórias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Carregando e Processando Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">RAIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vinculos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Vínculos Ativos em 31/12 – RAIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./remuneracao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Remuneração dos Vínculos Ativos - RAIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./desligamentos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Vínculos Desligados em 31/12 – RAIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./caged.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Novo CAGED</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./movimentacoes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Movimentações – Novo CAGED</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./admitidos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Remuneração dos Admitidos – Novo CAGED</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./narrativas.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Interligando Dados e Construindo Narrativas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Notas Metodológicas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agradecimentos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Agradecimentos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Interligando Dados e Construindo Narrativas</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A análise dos dados da RAIS e do Novo CAGED para o período de 2022 a 2025 permitiu mapear a dinâmica atual do mercado de trabalho formal da arqueologia no Brasil. O objetivo deste levantamento não foi esgotar todas as possibilidades analíticas desses registros administrativos, mas sim apresentar os principais padrões identificados por meio de gráficos interativos e tabelas. Para garantir transparência e reprodutibilidade, o script em R foi disponibilizado em cada painel, permitindo que outros pesquisadores verifiquem os procedimentos e explorem variáveis adicionais não contempladas aqui - ver <a href="notas.html" class="quarto-xref"><span>Capítulo 11</span></a>.</p>
<p>O panorama revelado mostra um mercado de trabalho marcado por avanços pontuais seguido de retração. A arqueologia formal demonstra alta sensibilidade a eventos conjunturais: as contratações crescem quando grandes projetos de licenciamento ambiental demandam vínculos celetistas, e encolhem quando obras são paralisadas ou concluídas, provocando perda da capacidade de retenção da força de trabalho. O biênio 2023–2024 ilustra bem essa oscilação: 2023 registrou um boom de contratações e maior poder de escolha para os profissionais, enquanto 2024 trouxe uma reversão desse cenário.</p>
<p>Geograficamente, a contratação de arqueólogos permanece concentrada na Região Sudeste. Contudo, o Nordeste emerge como polo de expansão, com destaque para Pernambuco, onde empresas locais vêm ampliando a oferta de empregos formais. Em contrapartida, a Região Norte apresenta as menores oportunidades de trabalho, com seus estabelecimentos contendo poucos contratos que exigem vínculos celetista, embora esse cenário venha se alterando paulatinamente.</p>
<p>O perfil de qualificação exigido pelo mercado formal revela uma dinâmica estrutural importante. A maioria das vagas demanda apenas graduados, com procura limitada por pós-graduados - mestres e doutores são poucos requisitados nos anúncios e contratos celetistas. Esse padrão favorece a contratação de profissionais experientes em campo, mas sem titulação superior, criando um mercado que valoriza prática e disponibilidade mais do que credenciais acadêmicas avançadas.</p>
<p>Essa lógica explica a concentração etária observada: a faixa de 30 a 39 anos é a mais numerosa no emprego formal. Trata-se de profissionais que se graduaram entre o final dos anos 2000 e meados da década de 2010 - período de expansão dos cursos de graduação em Arqueologia no Brasil. Com experiência acumulada em trabalhos de campo, mas sem mestrado ou doutorado, esse contingente tornou-se o alvo preferencial das consultorias privadas, que encontram nele um equilíbrio entre experiência e custo. A tendência natural é que esse grupo, à medida que envelheça, migre progressivamente para a faixa de 40 a 49 anos, ampliando o volume desse grupo na próxima década.</p>
<p>Já a menor proporção de profissionais acima de 40 anos resulta de múltiplos fatores. Há quem transite para a abertura de suas próprias consultorias, quem migre para cargos de gestão, quem se aposente ou quem simplesmente mude de carreira. Soma-se a isso o fator histórico-educacional: as faixas mais antigas são naturalmente menores comparado ao crescimento de formados na área.</p>
<p>Situação um pouco diferente para os jovens arqueólogos recém-formados, que não acompanham a expansão da profissão. Há baixa contratação dessa faixa, o que empurra essa categoria a buscar experiências fora do mercado formal. Como os jovens profissionais possuem menor reposição, a tendência é de envelhecimento na composição da força de trabalho formal.</p>
<p>Os pós-graduados, por sua vez, sem espaço no setor privado, que raramente valoriza a titulação superior com salários proporcionais, acabam migrando para a carreira acadêmica ou se formalizando como prestadores de serviço autônomo, muitas vezes via MEI. Assim, a pós-graduação não se converte, no mercado formal, em vantagem competitiva para o vínculo celetista.</p>
<p>No recorte por gênero, os registros administrativos consultados revelam uma composição que exige leitura cuidadosa e contextualizada. Em 2025, os homens concentraram 56,9% dos vínculos formais, contra 43,1% das mulheres. Dentro desse universo formal, contudo, as arqueólogas ocupam posição mais favorável no centro e na base da distribuição salarial.</p>
<p>Essa leitura, porém, descreve apenas o mercado formal. Duas pesquisas amostrais recentes, aplicadas diretamente à comunidade arqueológica, permitem situar esse achado em escala mais ampla - e ambas convergem para a mesma direção.</p>
<p>O primeiro levantamento, conduzido pelo Projeto Perfis com 506 respondentes e divulgado por Caromano <em>et al.</em> <span class="citation" data-cites="caromano2025panorama">(<a href="referencias.html#ref-caromano2025panorama" role="doc-biblioref">2025</a>)</span>, mostra que 54% dos profissionais que atuam em arqueologia no Brasil se identificam como mulheres cisgênero, contra 42% de homens cisgênero; os demais se identificam como pessoas não binárias, outros e não responderam. A proporção é coerente com a estimativa populacional de 2.117 profissionais, dos quais aproximadamente 1.112 seriam mulheres <span class="citation" data-cites="gaspar2020arqueologia">(<a href="referencias.html#ref-gaspar2020arqueologia" role="doc-biblioref">GASPAR et al., 2020</a>)</span>.</p>
<p>O segundo levantamento, realizado pelo Grupo de Trabalho de Licenciamento Ambiental da Sociedade de Arqueologia Brasileira (GTLA‑SAB) junto a 205 profissionais que atuam especificamente nesse mercado, chega a um resultado que espelha quase exatamente o dos registros administrativos: entre os profissionais autônomos no licenciamento ambiental, 54,7% são homens cisgênero e 41,9% são mulheres cisgênero <span class="citation" data-cites="gtla2025licenciamento">(<a href="referencias.html#ref-gtla2025licenciamento" role="doc-biblioref">Wittmann et al., 2025</a>)</span>. Os próprios autores comentam que as arqueólogas não se destacam proporcionalmente ao tamanho populacional que representam na comunidade.</p>
<p>A convergência entre três fontes construídas por métodos que não se comunicam - registros administrativos preenchidos pelo empregador, questionário aberto à comunidade profissional e questionário dirigido ao nicho do licenciamento ambiental - descrevem o mesmo desenho:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 45%">
<col style="width: 9%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Fonte</th>
<th>O que mede</th>
<th>Homens</th>
<th>Mulheres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gaspar <em>et al.</em> (2020)</td>
<td>Comunidade arqueológica (n= 2.117)</td>
<td>47,3%</td>
<td>52,5%</td>
</tr>
<tr class="even">
<td>Caromano <em>et al.</em> (2025)</td>
<td>Amostra da comunidade (n= 506)</td>
<td>42%</td>
<td>54%</td>
</tr>
<tr class="odd">
<td>RAIS (2025)</td>
<td>Vínculos formais ativos (n= 383)</td>
<td>56,9%</td>
<td>43,1%</td>
</tr>
<tr class="even">
<td>GTLA-SAB (2025)</td>
<td>Autônomos no licenciamento (n= 148)</td>
<td>54,7%</td>
<td>41,9%</td>
</tr>
</tbody>
</table>
<p>As arqueólogas são, portanto, maioria na profissão e minoria nas relações de trabalho. A dissociação entre essas duas posições se materializa na pesquisa do Projeto Perfis: apenas 13% das mulheres declararam possuir vínculo celetista, contra 23% dos homens; e 11% delas se declararam desempregadas, frente a 8% deles.</p>
<p>Esse contraste reposiciona a interpretação da diferença salarial observada nas seções anteriores. É verdade que, entre os vínculos formais captados pela RAIS, as arqueólogas apresentaram remuneração mediana superior à dos arqueólogos em 2025. Porém, essa medida descreve um subconjunto selecionado: as profissionais que conseguiram emprego formal. Quando se observa o universo da categoria, o enquadramento muda: Caromano <em>et al.</em> <span class="citation" data-cites="caromano2025panorama">(<a href="referencias.html#ref-caromano2025panorama" role="doc-biblioref">2025</a>)</span> registram que as mulheres predominam justamente na faixa de renda de 1 a 2 salários mínimos, superando os homens apenas de forma marginal nas faixas de 5 e 9 salários mínimos. A vantagem salarial feminina detectada nos registros administrativos, portanto, não representa a realidade da maioria das arqueólogas brasileiras; ela descreve a exceção do funil seletivo - a parcela que logrou ingressar e permanecer no mercado formal.</p>
<p>A comparação entre as fontes permite dimensionar esse funil seletivo. Com 383 vínculos ativos em 2025 e um universo profissional estimado em 2.117 arqueólogos <span class="citation" data-cites="gaspar2020arqueologia">(<a href="referencias.html#ref-gaspar2020arqueologia" role="doc-biblioref">GASPAR et al., 2020</a>)</span> - estimativa de 2018, a mais recente disponível -, o mercado formal alcança cerca de um quinto da categoria. Tudo o que este artigo descreve refere-se a essa fração. Mais de quatro quintos da profissão permanecem invisíveis aos registros administrativos da ocupação de arqueólogo, dispersos entre MEIs, trabalhadores com código CBO distinto, consultores autônomos, docentes, profissionais em transição e desempregados.</p>
<p>Delimitado esse quadro, a vantagem salarial feminina observada no mercado formal permanece como questão em aberto. Essa situação possibilita testar hipóteses que este mesmo conjunto de dados permite investigar, mas que não foram contemplados neste estudo. É possível, por exemplo, que as mulheres estejam mais concentradas em vínculos do setor público e de instituições de ensino e pesquisa, cujas remunerações tendem a superar as praticadas pelas consultorias privadas. Outra possibilidade é o maior tempo médio de emprego, acumulando progressões e estabilidade que elevam seus rendimentos. Pode-se também supor que estejam distribuídas de forma distinta entre as regiões do país, com presença mais acentuada em empresas sediadas em áreas economicamente mais dinâmicas. O cruzamento sistemático dessas variáveis com o sexo constitui a próxima etapa natural desta investigação e é justamente o que permitirá substituir conjecturas por evidências sobre as causas da diferença salarial observada.</p>
<p>Quanto à menor inserção feminina no mercado formal - agravada pelo aumento constante de desligamentos entre arqueólogas -, as limitações das bases administrativas impõem a necessidade de estudos amostrais sistemáticos para capturar dados de quem atua fora dos vínculos da ocupação de arqueólogo, onde se concentra a maior parcela da força de trabalho. Nesse sentido, a pesquisa de Machado e Mageste <span class="citation" data-cites="machado2024arqueologos">(<a href="referencias.html#ref-machado2024arqueologos" role="doc-biblioref">2024</a>)</span> propôs uma metodologia para mapear arqueólogos que atuam como MEI. Contudo, a replicação dessa abordagem encontra um obstáculo objetivo: desde novembro de 2023, a Receita Federal descontinuou o campo “nome fantasia” nos <a href="https://www.gov.br/empresas-e-negocios/pt-br/empreendedor/perguntas-frequentes/como-e-feita-a-formalizacao-do-mei/posso-cadastrar-no-nome-fantasia" title="link de acesso ao conteúdo">registros de MEI</a>, inviabilizando a estratégia de identificação baseada nesse atributo.</p>
<p>Cabe registrar as limitações inerentes às próprias pesquisas amostrais utilizadas. O questionário do Projeto Perfis esteve aberto entre junho e dezembro de 2022; o do GTLA‑SAB, entre maio e agosto de 2023. Ambos aplicados no formato digital, por convites via e-mail e divulgação em redes sociais. Contudo, sem continuidade temporal, pesquisas amostrais captam apenas retratos pontuais, não trajetórias. E sem elas, os registros administrativos descrevem somente a minoria formalizada. As duas fontes são complementares e indispensáveis: os microdados oficiais fornecem a série temporal e a granularidade do emprego formal; as pesquisas amostrais revelam o que acontece fora dele.</p>
<p>Diante desse cenário, torna-se imperativo que pesquisas amostrais sejam realizadas de forma contínua, representativa e padronizada, constituindo um repositório histórico longitudinal. Somente com dados periódicos - tanto sobre o mercado formal quanto fora dele - será possível compreender a dinâmica temporal do trabalho arqueológico no Brasil, incluindo os fatores que condicionam a retenção, a transição e a precarização diferencial entre gêneros.</p>
<p>Em termos de capacidade remuneratória, o crescimento salarial nominal observado no quadriênio não se traduziu necessariamente em ganho real. Um arqueólogo que recebia R$ 4.000 em 2022 estava na faixa de três a quatro salários mínimos; se esse mesmo profissional passa a receber R$ 4.500 em 2025, sua remuneração cai para a faixa de dois a três salários mínimos, dado o reajuste salarial nacional. Em posições relativas ao salário mínimo, houve rebaixamento de faixa, não ascensão. Nesse sentido, a categoria vivencia desvalorização salarial, com a maioria recebendo menos de 3 salários mínimos e com poucas perspectivas de acesso a remunerações elevadas.</p>
<p>A dependência do licenciamento ambiental é o fio condutor que atravessa todas essas dinâmicas. O crescimento de vínculos e salários nominais concentra-se no setor privado, especialmente nas consultorias que atendem demandas de obras licenciáveis. Exceções existem, mas ainda não configuram novas fronteiras de empregabilidade. O setor público, por outro lado, responde por uma participação minoritária, com poucos concursos e baixa absorção de profissionais - um contrassenso diante da densidade do patrimônio arqueológico brasileiro e da necessidade de gestão desses bens culturais. A predominância de projetos de curta duração gera um ciclo de alta rotatividade que impede a construção de estabilidade para a maioria dos trabalhadores.</p>
<p>Diante desse quadro, a mobilização coletiva emerge como caminho necessário. O levantamento do GTLA‑SAB <span class="citation" data-cites="gtla2025licenciamento">(<a href="referencias.html#ref-gtla2025licenciamento" role="doc-biblioref">Wittmann et al., 2025</a>)</span> revela que entre os profissionais autônomos que atuam no licenciamento ambiental, 74% apontaram a ausência de um sindicato ou conselho profissional como o principal problema da categoria. Essa percepção é acompanhada por queixas sobre salários e diárias insuficientes, instabilidade no emprego e acúmulo de funções. A convergência desses diagnósticos aponta para uma lacuna institucional: sem uma entidade de representação coletiva, a categoria carece de instrumentos para negociar pisos salariais, padronizar condições de trabalho e pressionar por políticas públicas de contratação.</p>
<p>É precisamente por isso que o sindicato se apresenta como a instância institucional mais adequada para articular essas demandas. Por meio dele, é possível construir estratégias para ampliar a presença de arqueólogos em instituições públicas, diversificar as fontes de contratação - incluindo editais de fomento cultural como a Política Nacional Aldir Blanc de Fomento à Cultura (<a href="https://www.gov.br/cultura/pt-br/assuntos/acoes-programas-e-politicas/politica-nacional-aldir-blanc-de-fomento-a-cultura" title="Link de acesso para a PNAB">PNAB</a>) -, propor e defender pisos salariais mínimos, fortalecer a transição de contratos informais para vínculos celetistas e instituir a realização periódica de pesquisas amostrais que monitorem a dinâmica do mercado. Sem essa articulação coletiva, a profissão continuará crescendo em número de vínculos, mas sem traduzir esse crescimento em segurança, estabilidade e valorização real para seus profissionais.</p>


<div id="refs" class="references csl-bib-body" data-entry-spacing="1" role="list" style="display: none">
<div id="ref-allaire2026quarto" class="csl-entry" role="listitem">
ALLAIRE, J. J. <em>et al.</em> <strong>Quarto</strong>. Software de publicação técnica, 2026. Disponível em: &lt;<a href="https://quarto.org/">https://quarto.org/</a>&gt;. Acesso em: 27 ago. 2026
</div>
<div id="ref-nomefantasia" class="csl-entry" role="listitem">
BRASIL. EMPRESAS &amp; NEGÓCIOS. <strong>Posso cadastrar <span>Nome</span> <span>Fantasia</span> no meu <span>CNPJ</span>?</strong> Disponível em: &lt;<a href="https://www.gov.br/empresas-e-negocios/pt-br/empreendedor/perguntas-frequentes/como-e-feita-a-formalizacao-do-mei/posso-cadastrar-no-nome-fantasia">https://www.gov.br/empresas-e-negocios/pt-br/empreendedor/perguntas-frequentes/como-e-feita-a-formalizacao-do-mei/posso-cadastrar-no-nome-fantasia</a>&gt;. Acesso em: 27 ago. 2026.
</div>
<div id="ref-esocial2026" class="csl-entry" role="listitem">
BRASIL. GOVERNO FEDERAL. <strong><span>eSocial</span>: <span>Sistema</span> de <span>Escrituração</span> <span>Digital</span> das <span>Obrigações</span> <span>Previdenciárias</span>, <span>Trabalhistas</span> e <span>Fiscais</span></strong>. Disponível em: &lt;<a href="https://www.gov.br/esocial/pt-br">https://www.gov.br/esocial/pt-br</a>&gt;. Acesso em: 27 ago. 2026.
</div>
<div id="ref-minc2024pnab" class="csl-entry" role="listitem">
BRASIL. MINISTÉRIO DA CULTURA. <strong>Política <span>Nacional</span> <span>Aldir</span> <span>Blanc</span> de <span>Fomento</span> à <span>Cultura</span> (<span>PNAB</span>)</strong>. Disponível em: &lt;<a href="https://www.gov.br/cultura/pt-br/assuntos/acoes-programas-e-politicas/politica-nacional-aldir-blanc-de-fomento-a-cultura">https://www.gov.br/cultura/pt-br/assuntos/acoes-programas-e-politicas/politica-nacional-aldir-blanc-de-fomento-a-cultura</a>&gt;. Acesso em: 27 ago. 2026.
</div>
<div id="ref-mtemicrodados" class="csl-entry" role="listitem">
BRASIL. MINISTÉRIO DO TRABALHO E EMPREGO. <strong>Microdados <span>RAIS</span> e <span>CAGED</span></strong>. Disponível em: &lt;<a href="https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/estatisticas-trabalho/microdados-rais-e-caged">https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/estatisticas-trabalho/microdados-rais-e-caged</a>&gt;. Acesso em: 16 ago. 2026b.
</div>
<div id="ref-mtepdet" class="csl-entry" role="listitem">
BRASIL. MINISTÉRIO DO TRABALHO E EMPREGO. <strong>Programa de Disseminação das Estatísticas do Trabalho — <span>PDET</span></strong>. Disponível em: &lt;<a href="https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/estatisticas-trabalho">https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/estatisticas-trabalho</a>&gt;. Acesso em: 27 ago. 2026c.
</div>
<div id="ref-mte2026cbo" class="csl-entry" role="listitem">
BRASIL. MINISTÉRIO DO TRABALHO E EMPREGO. <strong>Classificação <span>Brasileira</span> de <span>Ocupações</span> — (<span>CBO</span>)</strong>. Disponível em: &lt;<a href="https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo">https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo</a>&gt;. Acesso em: 27 ago. 2026a.
</div>
<div id="ref-caromano2025panorama" class="csl-entry" role="listitem">
CAROMANO, Caroline Fernandes <em>et al.</em> <a href="https://doi.org/10.31048/c4gfep32">Panorama actual de las Arqueólogas en Brasil: desafíos y perspectivas</a>. <strong>Revista del Museo De Antropología</strong>, v. 18, n. 1, p. 457–470, 2025.
</div>
<div id="ref-gaspar2020arqueologia" class="csl-entry" role="listitem">
GASPAR, Meliam Viganó <em>et al.</em> <a href="https://doi.org/10.18224/hab.v18i1.8104">Quem somos nós? ou perfis da comunidade profissional arqueológica no Brasil: primeiras aproximações</a>. <strong>Revista Habitus - Revista do Instituto Goiano de Pré-História e Antropologia</strong>, v. 18, n. 1, p. 146–178, 2020.
</div>
<div id="ref-ibge2026cnae" class="csl-entry" role="listitem">
INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATÍSTICA (IBGE). <strong>Classificação <span>Nacional</span> de <span>Atividades</span> <span>Econômicas</span> — <span>CNAE</span> 2.0</strong>. Disponível em: &lt;<a href="https://concla.ibge.gov.br/classificacoes/por-tema/atividades-economicas/classificacao-nacional-de-atividades-economicas">https://concla.ibge.gov.br/classificacoes/por-tema/atividades-economicas/classificacao-nacional-de-atividades-economicas</a>&gt;. Acesso em: 27 ago. 2026.
</div>
<div id="ref-iphan2024edital" class="csl-entry" role="listitem">
INSTITUTO DO PATRIMÔNIO HISTÓRICO E ARTÍSTICO NACIONAL. <strong>Edital nº 1, de 3 de dezembro de 2024: Processo Seletivo Simplificado (PSS/IPHAN)</strong>. Diário Oficial da União (DOU), 2024. Disponível em: &lt;<a href="https://www.in.gov.br/web/dou/-/edital-n-1-de-3-de-dezembro-de-2024-599671293">https://www.in.gov.br/web/dou/-/edital-n-1-de-3-de-dezembro-de-2024-599671293</a>&gt;. Acesso em: 27 ago. 2026
</div>
<div id="ref-machado2024arqueologos" class="csl-entry" role="listitem">
MACHADO, Tacio Vieira; MAGESTE, Leandro Elias Canaan. <a href="https://doi.org/10.24885/sab.v37i1.1108">Os arqueólogos no mercado de trabalho e a realidade profissional no <span>Brasil</span></a>. <strong>Revista de Arqueologia</strong>, v. 37, n. 1, p. 202–226, 2024.
</div>
<div id="ref-rcore2026" class="csl-entry" role="listitem">
R CORE TEAM. <strong><a href="https://www.R-project.org/">R: A Language and Environment for Statistical Computing</a></strong>. Vienna, Austria: R Foundation for Statistical Computing, 2026.
</div>
<div id="ref-gtla2025licenciamento" class="csl-entry" role="listitem">
WITTMANN, Marcus A. S. <em>et al.</em> <a href="https://www.sabnet.org/download/download?ID_DOWNLOAD=835">Arqueologia em ação: o panorama atual das múltiplas perspectivas do trabalho arqueológico no licenciamento ambiental</a>. <em>In</em>: WITTMANN, Marcus A. S. <em>et al.</em> (Orgs.). <strong>Arqueologia no licenciamento ambiental: diagnósticos e perspectivas regionais</strong>. São Paulo: Tiki Books; SAB, 2025. p. 266–294.
</div>
</div>

</main> <!-- /main -->
<script>
// ───────────────────────────────────────────────────────────────────────────
//  Distribui as ações de repositório entre as duas colunas:
//
//    esquerda, no pé da lista de capítulos → "Ver o código fonte"
//                                            (apontando para a raiz do repo)
//    direita, ao fim de "Nesta seção"      → as demais ações (ex.: issue)
//
//  Também remove do cabeçalho o ícone duplicado que o Quarto cria a partir
//  de repo-url, e faz os links externos abrirem em nova aba.
// ───────────────────────────────────────────────────────────────────────────
(function () {

  var ABRIR_EM_NOVA_ABA = true;   // false para navegar na mesma aba

  function externo(a) {
    return a.protocol && /^https?:$/.test(a.protocol) &&
           a.hostname && a.hostname !== window.location.hostname;
  }
  function novaAba(a) {
    if (!ABRIR_EM_NOVA_ABA || !a || !externo(a)) return;
    a.setAttribute('target', '_blank');
    a.setAttribute('rel', 'noopener');
  }

  function ajustar() {
    var barra  = document.getElementById('quarto-sidebar');
    var margem = document.getElementById('quarto-margin-sidebar');
    var blocos = document.querySelectorAll('.toc-actions');
    if (!barra || !blocos.length) return;

    var principal = blocos[0];

    // remove as cópias que o Quarto repete no rodapé da página
    for (var i = 1; i < blocos.length; i++) {
      var pai = blocos[i].closest('.nav-footer-center, .nav-footer-left, .nav-footer-right');
      (pai || blocos[i]).remove();
    }

    // ── separa o link do código fonte ────────────────────────────────────
    var fonte = principal.querySelector('a[href*="/blob/"]');
    if (fonte) {
      var base = fonte.getAttribute('href').split('/blob/')[0];

      var icone = document.querySelector(
        '.sidebar-tools-main a.quarto-navigation-tool[href="' + base + '"]'
      );
      if (icone) icone.remove();

      fonte.setAttribute('href', base);      // encurta para a raiz do repositório

      var item = fonte.closest('li');
      var caixa = document.createElement('div');
      caixa.className = 'toc-actions';
      var lista = document.createElement('ul');
      lista.appendChild(item);               // move só este <li>
      caixa.appendChild(lista);

      var rodape = document.createElement('div');
      rodape.className = 'sidebar-fonte';
      rodape.appendChild(document.createElement('hr'));
      rodape.appendChild(caixa);
      barra.appendChild(rodape);
    }

    // ── o que sobrou (issue, edit…) fica na coluna da direita ────────────
    var restantes = principal.querySelectorAll('li');
    if (!restantes.length) {
      principal.remove();
    } else if (margem && !margem.contains(principal)) {
      // capítulos sem subtítulos não têm sumário: o Quarto joga o bloco no
      // rodapé da página; aqui ele é trazido para a margem, como nos demais
      principal.classList.add('toc-actions-soltas');
      margem.appendChild(principal);
    }

    // ── ícone: o Quarto só decora a primeira ação; as demais recebem
    //    <i class="bi empty">. Copia aqui o mesmo ícone para todas. ────────
    var modelo = document.querySelector('.toc-actions i.bi:not(.empty)');
    var classe = 'bi-github';
    if (modelo) {
      Array.prototype.forEach.call(modelo.classList, function (c) {
        if (c !== 'bi') classe = c;
      });
    }
    Array.prototype.forEach.call(
      document.querySelectorAll('.toc-actions i.bi.empty'),
      function (i) { i.classList.remove('empty'); i.classList.add(classe); }
    );

    Array.prototype.forEach.call(
      document.querySelectorAll('.sidebar-tools-main a, .toc-actions a'),
      novaAba
    );
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', ajustar);
  } else { ajustar(); }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./admitidos.html" class="pagination-link" aria-label="Remuneração dos Admitidos – Novo CAGED">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Remuneração dos Admitidos – Novo CAGED</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./notas.html" class="pagination-link" aria-label="Notas Metodológicas">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Notas Metodológicas</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/machadotm/dados_mte_rais_arqueo_22-24/blob/main/narrativas.qmd" class="toc-action"><i class="bi bi-github"></i>Código fonte do artigo</a></li><li><a href="https://github.com/machadotm/dados_mte_rais_arqueo_22-24/issues/new" class="toc-action"><i class="bi empty"></i>Relatar erro</a></li></ul></div></div></div></footer></body></html>